### ISSUE TITLE
Missing issue when you Try to Import from PROD to STG under PRO

### ISSUE THREAD

**Issue by amarroni** [AdobeDocs/commerce-cloud-service.en#11]
Issue in ./help/cloud-guide/deploy/staging-production.md
https://experienceleague.adobe.com/docs/commerce-cloud-service/user-guide/develop/deploy/staging-production.html

In order to import a db without issue you show display a possible error and the fix is creating a dump using this command:

php bin/ece-tools db-dump --remove-definers

Best,
Alejandro.

**Comment by hguthrie** [comment]
I do not know why this has been overlooked. I will address this today. Currently in technical review.

**Comment by hguthrie** [comment]
Done, should publish soon
