### ISSUE TITLE
Add the configuration for the plugins

### ISSUE THREAD

**Issue by ak77-prime** [AdobeDocs/commerce-cloud-service.en#12]
Issue in ./help/cloud-guide/services/opensearch.md

The same ``Additional search configuration`` indicated in https://experienceleague.adobe.com/docs/commerce-cloud-service/user-guide/configure/service/elasticsearch.html?lang=en should be copied over

**Comment by hguthrie** [comment]
Yeah, there is an OpenSearch update coming soon. I'll add this too. Thanks!

**Comment by hguthrie** [comment]
I have created a PR to add this content and it is under review with Cloud team.
