### ISSUE TITLE
Emphasize that this method doesn't apply to Pro Staging and Production environments

### ISSUE THREAD

**Issue by ak77-prime** [AdobeDocs/commerce-cloud-service.en#13]
Issue in ./help/cloud-guide/storage/snapshots.md

It is stated right at the outset:

You can back up and restore specific environments at any time using a snapshot. Snapshot options are available for all Starter environments and Pro Integration environments. **The snapshot feature does not apply to the Pro Staging and Production environments**.

**Item 1**: We should probably add a reminder throughout the rest of the article in case someone were to click on the anchor link or gets provided that link directly before they have the change to read the above note.

STOP: If you are working with the Pro Staging or Production environment, this step does not apply to you. Please submit a support request to request a backup with a specific date, time, and timezone.

**Item 2**: Also, to prevent any confusion, the example output given for the command below should not mention production :

```
To create a snapshot using the magento-cloud CLI:
...
Step 3: Create the snapshot

magento-cloud snapshot:create
Creating a snapshot of production // do not mention production
Waiting for the snapshot to complete...
```

**Comment by hguthrie** [comment]
There is an internal ticket for improvements to this content. I added your suggestion to the ticket. Thanks!
