### ISSUE TITLE
missing cross reference to other documentation

### ISSUE THREAD

**Issue by cgarrigues** [AdobeDocs/commerce-cloud-service.en#15]
Issue in ./help/cloud-guide/project/sendgrid.md
https://experienceleague.adobe.com/docs/commerce-cloud-service/user-guide/project/sendgrid.html

This page should include a reference to https://experienceleague.adobe.com/docs/commerce-admin/systems/communications/email-communications.html possibly when it suggests "to improve message delivery rate, you can upgrade from Starter to Pro or use your own SMTP server or email delivery service provider." as this is where you configure your own smtp server or email provider.

**Comment by hguthrie** [comment]
Sounds like a good idea. Thanks!
