### ISSUE TITLE
We should not recommend adding auth.json to GIT

### ISSUE THREAD

**Issue by ak77-prime** [AdobeDocs/commerce-cloud-service.en#16]
Issue in ./help/cloud-guide/development/authentication-keys.md

We don't recommend committing auth.json to GIT for security reasons. 

Suggest retaining the second method only, i.e., via the ``env:COMPOSER_AUTH`` variable

**Comment by hguthrie** [comment]
Both methods are valid for different reasons. This method is also mentioned in the README files in the code repositories, particularly for working with Docker. I think it would be wise to add better guidance in the topic that you mentioned, though, so will plan an update.
