### ISSUE TITLE
Notification Channels are replaced by Workflows

### ISSUE THREAD

**Issue by alanbort** [AdobeDocs/commerce-cloud-service.en#21]
Issue in ./help/cloud-guide/monitor/new-relic.md

The section about notification channels should be updated to reflect the new workflows feature that was implemented and deployed to all Adobe Commerce Cloud customers during Q1 2023

**Comment by hguthrie** [comment]
Thanks @alanbort  I will take a look at it.

**Comment by hguthrie** [comment]
Oh! This has been updated to show Workflows in New Relic.
https://experienceleague.adobe.com/docs/commerce-cloud-service/user-guide/monitor/new-relic.html#set-up-a-workflow-for-notifications
