### ISSUE TITLE
Missing mandatory parameter on the command magento-cloud integration:add

### ISSUE THREAD

**Issue by JoaquinBecerraAtValtech** [AdobeDocs/commerce-cloud-service.en#22]
Issue in ./help/cloud-guide/integrations/github.md

In the example, and description of the command of integration creation:

`magento-cloud integration:add --type=github --project=<project-ID> --token=<your-GitHub-token> {--repository=USER/REPOSITORY | --repository=ORGANIZATION/REPOSITORY} [--build-pull-requests={true|false} --fetch-branches={true|false}`

Is missing the mandatory parameter --base-url (an example and a good description of this parameter would be nice)

Also other parameter are not included in the command: 

--build-draft-pull-requests  --build-pull-requests-post-merge  --pull-requests-clone-parent-data --prune-branches

And are asked by the magento-cloud console

**Comment by JoaquinBecerraAtValtech** [comment]
After some time and with the help of Adobe Commerce Cloud support, I was able to create the integration, but I had to use Magento Cloud CLI version 1.40.0 (without using the base-url parameter).

In version 1.42.0 the base-url parameter is mandatory and it is not clear what should be sent in this case.

The documentation of the integration with GitLab is clearer in this regard:
https://experienceleague.adobe.com/docs/commerce-cloud-service/user-guide/dev-tools/integrations/gitlab.html

**Comment by hguthrie** [comment]
Thank you for pointing out some changes since the latest update. We will revisit this integration process.
