### ISSUE TITLE
A link on this page redirects to a scam site

### ISSUE THREAD

**Issue by willryan-stemcell** [AdobeDocs/commerce-cloud-service.en#24]
Issue in ./help/cloud-guide/launch/checklist.md

The link in this command redirects to a fake virus scam site:
`php bin/magento setup:store-config:set --base-url="https://www.your-domain.com/"`

I suggest changing it to some other URL that Adobe has control over.

**Comment by hguthrie** [comment]
The topic was updated to use a variable.
