### ISSUE TITLE
"Manage custom VCL snippets" not rendered

### ISSUE THREAD

**Issue by ak77-prime** [AdobeDocs/commerce-cloud-service.en#32]
Issue in ./help/cloud-guide/cdn/fastly-vcl-blocking.md

The placeholder doesn't appear to be rendered: https://experienceleague.adobe.com/docs/commerce-cloud-service/user-guide/cdn/custom-vcl-snippets/fastly-vcl-blocking.html?lang=en 

```
Expand Full Page Cache > Fastly Configuration > Custom VCL Snippets.

![Manage custom VCL snippets] // <--
```

**Comment by hguthrie** [comment]
Updated in main. Thanks for pointing it out.
