### ISSUE TITLE
Missing runtime property

### ISSUE THREAD

**Issue by joaquin-becerra** [AdobeDocs/commerce-cloud-service.en#6]
Issue in ./help/cloud-guide/application/properties.md

You can put some configuration in this file regarding the php modules to add:

`# Enable extensions required by Magento 2
runtime:
    extensions:
        - xsl
        - newrelic
        - sodium`

see: https://experienceleague.adobe.com/docs/commerce-cloud-service/user-guide/configure/app/php-settings.html?lang=en

**Comment by hguthrie** [comment]
Ah... we need to add the `runtime` property in the properties table and add appropriate content. 👍 
Thanks!
