### ISSUE TITLE
Missing magento-vars.php reference

### ISSUE THREAD

**Issue by joaquin-becerra** [AdobeDocs/commerce-cloud-service.en#7]
Issue in ./help/cloud-guide/environment/overview.md

Looks like you are missing the magento-vars.php reference

Is not a configuration file?

**Comment by hguthrie** [comment]
Well, it is mentioned in the [Project structure](https://experienceleague.adobe.com/docs/commerce-cloud-service/user-guide/project/file-structure.html), but mainly used for [defining multiple sites](https://experienceleague.adobe.com/docs/commerce-cloud-service/user-guide/configure-store/multiple-sites.html#set-up-websites%2C-stores%2C-and-store-views).
