### ISSUE TITLE
In witch file you define the worker config?

### ISSUE THREAD

**Issue by joaquin-becerra** [AdobeDocs/commerce-cloud-service.en#8]
Issue in ./help/cloud-guide/application/workers-property.md

In witch file you define the worker config?

**Comment by hguthrie** [comment]
It is a property of the `.magento.app.yaml` file, as [listed in the Properties table](https://experienceleague.adobe.com/docs/commerce-cloud-service/user-guide/configure/app/properties/properties.html).
However, the Workers topic should indicate that a little more clearly.
Thanks for pointing out this gap!
